James/hardhat plugin
AstarNetwork/astar.js pull request #4
Opened 2021-12-10 21:16 UTC by jim4067

2021-12-10 21:44 UTC, drewstone requested changes

2021-12-10 21:44 UTC, drewstone commented on packages/hardhat-astar-plugin/.editorconfig
> +[*]
You can remove this file and add to `.gitignore`

2021-12-10 21:44 UTC, drewstone commented on packages/hardhat-astar-plugin/package-lock.json
> +{
This file shouldn't be necessary afaik. Best to use yarn but overall should be contained in a master `yarn.lock` if the resolutions are properly set up.

2021-12-10 21:44 UTC, drewstone commented on packages/hardhat-astar-plugin/test/project.test.ts
> +    describe("sayHello", function () {
These should be changed to use `sdk-core` API and test the evm conversion tools.

2021-12-12 20:43 UTC, drewstone commented
CI has errors on tests and linting.

2021-12-13 10:03 UTC, jim4067 commented
> CI has errors on tests and linting.

Trying to fix them.

2021-12-20 20:34 UTC, merged